services:
#  tracker_price_robot:
#    container_name: tracker_price_robot
#    hostname: tracker_price_robot
#    build:
#      context: .
#      dockerfile: src/Dockerfile
#    restart: on-failure
#    env_file:
#      - ./src/.env
#    ports:
#      - "9000:8000"
#    depends_on:
#      tracker_price_robot_postgres:
#        condition: service_healthy
#    networks:
#      - proxy_net

  tracker_price_robot_postgres:
    container_name: tracker_price_robot_postgres
    hostname: tracker_price_robot_postgres
    image: postgres:16.5-alpine
    env_file:
      - ./postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/migrations:/docker-entrypoint-initdb.d
    networks:
      - proxy_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d tracker_price_robot_postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres:


networks:
  proxy_net:
    name: proxy
    driver: bridge
